spring.application.name=patient-record-management

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsASuperSecretKeyForPatientRecordManagementPlatform2026ThisMustBeLongEnough
jwt.expiration=86400000