spring.application.name=patient-record-management

spring.datasource.url=jdbc:mysql://localhost:3306/patient_record_management
spring.datasource.username=root
spring.datasource.password=STRONGPASSWORD#8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsASuperSecretKeyForPatientRecordManagementPlatform2026ThisMustBeLongEnough
jwt.expiration=86400000